spring:
  application:
    name: develop-server
eureka:
  instance:
    hostname: localhost
    ip: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5551/eureka/
