server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/think_free?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: comhdoit
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
think:
  authority:
    logined-callback: base
  checkmac:
    slat: iMmiThink
    enabled: false
    allowlist: /v2/api-docs,/api/v1/file/download/downFile,/api/v1/process/activiti/pdImage,/api/v1/file/upload/uploadChunk
  cors:
    enabled: true
    exposed-header: token,refreshToken,hasNewToken