server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/think_free?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: comhdoit
logging:
  config: classpath:logback-spring-prod.xml
think:
  authority:
    logined-callback: base
  checkmac:
    slat: iMmiThink
    enabled: true
    allowlist: /v2/api-docs,/api/v1/authority/download/downFile